# Generated by Django 2.2.28 on 2023-11-12 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('couleur_pref', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=200)),
                ('nb_nuit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id_chambre', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('couleur', models.CharField(max_length=100)),
                ('propre', models.BooleanField()),
                ('photo', models.CharField(max_length=200)),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Client')),
            ],
        ),
    ]
