# Generated by Django 2.2.28 on 2023-11-12 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='occupant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Client'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='photo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
