# Generated by Django 2.2.28 on 2023-11-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20231112_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_client',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
