# Generated by Django 2.2.28 on 2023-11-13 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20231113_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='occupant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Client'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='photo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
